# Generated by Django 5.0.14 on 2026-06-16 07:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_months', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVÉE', 'Approuvée'), ('DÉCAISSÉE', 'Décaissée'), ('REJETÉE', 'Rejetée')], default='SOUMISE', max_length=15)),
                ('eligibility_score', models.IntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_assigned', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de crédit',
                'verbose_name_plural': 'Demandes de crédit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CNI', "Carte Nationale d'Identité / Passeport"), ('JUSTIFICATIF_REVENUS', 'Justificatif de revenus / Relevé'), ('AUTRE', 'Autre pièce')], max_length=30)),
                ('file', models.FileField(upload_to='credit_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credits.creditrequest')),
            ],
            options={
                'verbose_name': 'Document justificatif',
                'verbose_name_plural': 'Documents justificatifs',
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYÉE', 'Payée'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=15)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='credits.creditrequest')),
            ],
            options={
                'verbose_name': 'Échéance de remboursement',
                'verbose_name_plural': 'Échéances de remboursement',
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (Orange/Wave/MTN)'), ('ESPÈCES', 'Espèces'), ('VIREMENT', 'Virement bancaire')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('late_penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credits.repaymentschedule')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date'],
            },
        ),
    ]
