# Generated by Django 5.0.14 on 2026-06-16 07:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coverage_type', models.CharField(choices=[('VIE', 'Assurance Vie'), ('DÉCÈS_INVALIDITÉ', 'Décès et Invalidité'), ('MULTIRISQUE', 'Multirisque')], max_length=20)),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_months', models.IntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Produit d'assurance",
                'verbose_name_plural': "Produits d'assurance",
            },
        ),
        migrations.CreateModel(
            name='InsuranceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRÉE', 'Expirée'), ('ANNULÉE', 'Annulée'), ('EN_ATTENTE', 'En attente')], default='ACTIVE', max_length=15)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_phone', models.CharField(max_length=20)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('notification_sent_15days', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='insurance.insuranceproduct')),
            ],
            options={
                'verbose_name': "Souscription d'assurance",
                'verbose_name_plural': "Souscriptions d'assurance",
                'ordering': ['-created_at'],
            },
        ),
    ]
